#!/bin/bash

readonly LEARNING_RATE=1e-02
readonly DATE=$(date +%m%d)
readonly SEED=42
readonly TRAINING_EPOCH=400
readonly CANCEL_EPOCH=200
readonly HELP_EPOCH=10000
readonly BSZ=64
readonly WEIGHTDECAY=0
readonly USE_REGR=1
readonly HECOEFF=1e-2
readonly CLIPPING_VALUE=0
readonly CLIPPING_NORM=0 # using norm as the clipping
readonly OPTM="sgd"
readonly TRAINING_SIZE=0.0
readonly USE_POW=0
readonly ETA=0
readonly SSEPOCH=0
readonly LOSS_TYPE1=1
readonly LOSS_TYPE2=0
readonly LOSS_TYPE2_COEF=0
readonly LOSS_ORTHO=0
readonly ORTHO=0
readonly MT="resnet18" # resnet18, efficientnetb0, efficientnet_v2, wideresnet-16-8
readonly NUM_WORKERS=0 # modify this accordingly
readonly LOSS_FUNC="CE" # CE, leaky_ramp, squared_hinge, logistic_hinge, 
readonly LEAKY=0
readonly TAU=2.0
readonly WEIGHT_CAP=1
readonly CAP_TYPE="frob" # frob or spectral
readonly MRES=0
readonly PHI_NORM=1
readonly F_MAX_NORM=50.0

nohup python -u train.py \
    --learning_rate=${LEARNING_RATE} \
    --eta=${ETA} \
    --training_date=${DATE} \
    --mnetwork=${MRES} \
    --model=${MT} \
    --loss_func=${LOSS_FUNC} \
    --leaky_coef=${LEAKY} \
    --random_seed=${SEED} \
    --epochs=${TRAINING_EPOCH} \
    --num_workers=${NUM_WORKERS} \
    --scheduler_stop_epoch=${SSEPOCH} \
    --tau=${TAU} \
    --weight_cap=${WEIGHT_CAP} \
    --cap_type=${CAP_TYPE} \
    --f_max_norm=${F_MAX_NORM} \
    --cancel_epoch=${CANCEL_EPOCH} \
    --help_epoch=${HELP_EPOCH} \
    --batch_size=${BSZ} \
    --weight_decay=${WEIGHTDECAY} \
    --use_regulation=${USE_REGR} \
    --phi_norm=${PHI_NORM} \
    --use_pow=${USE_POW} \
    --lambda=${HECOEFF} \
    --loss_type1=${LOSS_TYPE1} \
    --loss_type2=${LOSS_TYPE2} \
    --loss_type2_coef=${LOSS_TYPE2_COEF} \
    --loss_ortho=${LOSS_ORTHO} \
    --ortho=${ORTHO} \
    --clip_value=${CLIPPING_VALUE} \
    --clip_norm=${CLIPPING_NORM} \
    --optim_type=${OPTM} \
    --training_size=${TRAINING_SIZE} \
    > Seed${SEED}_Date${DATE}_MT${MT}_MRes${MRES}_EP${TRAINING_EPOCH}_CANEP${CANCEL_EPOCH}_TSZ${TRAINING_SIZE}_BSZ${BSZ}_LF${LOSS_FUNC}_LKCF${LEAKY}_OPTM${OPTM}_LR${LEARNING_RATE}_WD${WEIGHTDECAY}_REGR${USE_REGR}_PHIN${PHI_NORM}_LAMBDA${HECOEFF}_TAU${TAU}_LT1${LOSS_TYPE1}_WCAP${WEIGHT_CAP}_CAPT${CAP_TYPE}_FMAX${F_MAX_NORM}_trainlog.txt 2>&1 &